import { createRequire } from 'module'
const require = createRequire(import.meta.url)
const { Client } = require('pg')
const c = new Client({host:'zephyr.proxy.rlwy.net',port:24934,database:'truespend',user:'truespend',password:'<REDACTED_ROTATE_ME>',ssl:false})
await c.connect()
const q = async(lbl, sql) => { const r = await c.query(sql); console.log(`${lbl}: ${r.rows[0]?.count ?? r.rows[0]?.c ?? JSON.stringify(r.rows[0])}`) }
await q('tickets (mock)', "SELECT count(*) FROM tickets WHERE reference IN ('TS-2026-0101','TS-2026-0118','TS-2026-0122','TS-2026-0125','TS-2026-0130','TS-2026-0133')")
await q('decisions', "SELECT count(*) FROM decisions")
await q('trace_log', "SELECT count(*) FROM trace_log")
await q('license_entitlements', "SELECT count(*) FROM license_entitlements")
await q('contracts_expiring', "SELECT count(*) FROM contracts_expiring")
await q('license_waste_report', "SELECT count(*) FROM license_waste_report")
await q('budget_buckets', "SELECT count(*) FROM budget_buckets")
await q('workflow_runs', "SELECT count(*) FROM workflow_runs")
await q('compliance_checks', "SELECT count(*) FROM compliance_checks")
console.log('\nOperations Board tickets:')
const r = await c.query("SELECT reference, status, title FROM open_tickets_board ORDER BY sort_priority, created_at")
r.rows.forEach(t => console.log(`  ${t.reference} [${t.status}] ${t.title?.substring(0,60)}`))
await c.end()
